### ISSUE TITLE
Can't execute AjaxMutator

### ISSUE THREAD

**Issue by luispigu** [knishiura-lab/AjaxMutator#1]
Hello,

I imported this tool to eclipse and i tried to execute this but there were several errors like below messages.

Would you please explain how to solve this problem?
Thank you!

![ajaxmutator](https://f.cloud.github.com/assets/1230159/1732156/5b9973aa-6318-11e3-9f0f-11a5b66938e6.PNG)

**Comment by knishiura-lab** [comment]
Thanks for trying AjaxMutator and sorry for late reply.

It seems that you are using JDK 1.5 or earlier. I develop AjaxMutator using JDK 1.7, so I recommend you to update to Java 1.7.

In addition, I recently added dependency to [JavaFx](http://www.oracle.com/technetwork/java/javafx/overview/index.html), and there is issue around it. You may have to run following command (for details, see http://zenjava.com/javafx/maven/fix-classpath.html )

> mvn com.zenjava:javafx-maven-plugin:2.0:fix-classpath

**Comment by knishiura-lab** [comment]
I keep this issue opened, so if you have further question, please feel feel to ask here.

**Comment by luispigu** [comment]
I am sorry for my late answer.
Actually, I solved this problem by using your suggestion.
It's related to Java version.

Thank you!
